apiVersion: v1
kind: Service
metadata:
  name: kubescale-backend-service
spec:
  selector:
    app: kubescale-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
