apiVersion: v1
kind: Service
metadata:
  name: kubescale-frontend-service
spec:
  selector:
    app: kubescale-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
